#:kivy 2.3.0

<QuickFunctionalityTestScreen>
    md_bg_color: '#13202E'

    TopBar:

    MDBoxLayout:
        adaptive_size: True
        pos_hint: {'top': .975, 'center_x': .5}
        StatusBar:

    MDBoxLayout:
        adaptive_size: True
        orientation: 'vertical'
        pos_hint: {'center_x': .5, 'center_y': .5}
        spacing: '30dp'

        MDBoxLayout:
            adaptive_size: True
            orientation: 'vertical'
            spacing: dp(12)
            pos_hint: {'center_x': .5}
            padding: [0, dp(50), 0, 0]
        
            MDLabel:
                id: quick_functionality_test_title
                text: 'QUICK FUNCTIONALITY TEST'
                font_style: 'Headline'
                role: 'medium'
                theme_text_color: 'Custom'
                text_color: app.theme_cls.secondaryColor
                adaptive_size: True
                pos_hint: {'center_x': .5}
            
            MDBoxLayout:
                adaptive_size: True
                orientation: 'vertical'
                spacing: dp(8)
                pos_hint: {'center_x': .5}
                padding: [dp(12), dp(12), dp(12), 0]
                
                MDBoxLayout:
                    adaptive_size: True
                    orientation: 'vertical'
                    spacing: dp(8)
                    pos_hint: {'center_x': .5}
                    
                    MDLabel:
                        id: quick_functionality_test_description_line1
                        text: 'The test alternates between Run and Purge modes every 60 seconds.'
                        theme_text_color: 'Custom'
                        text_color: app.theme_cls.primaryColor
                        adaptive_size: True
                        size_hint_x: .9
                        pos_hint: {'center_x': .5}
                        halign: 'center'
                    
                    MDLabel:
                        id: quick_functionality_test_description_line2
                        text: 'The test will end after 4 minutes.'
                        theme_text_color: 'Custom'
                        text_color: app.theme_cls.primaryColor
                        adaptive_size: True
                        size_hint_x: .9
                        pos_hint: {'center_x': .5}
                        halign: 'center'
                        
                
                # Timer display
                MDBoxLayout:
                    adaptive_size: True
                    spacing: '10dp'
                    pos_hint: {'center_x': .5}
                    padding: [0, dp(12), 0, 0]
                    
                    MDLabel:
                        id: time_remaining
                        text: 'TIME REMAINING'
                        theme_text_color: 'Custom'
                        text_color: app.theme_cls.onSurfaceColor
                        font_size: sp(17)
                        adaptive_size: True
                        pos_hint: {'center_y': .5}
                    
                    MDButton:
                        radius: dp(2)
                        theme_width: 'Custom'
                        theme_height: 'Custom'
                        width: dp(62)
                        height: dp(30)
                        padding: 0
                        theme_bg_color: 'Custom'
                        md_bg_color: app.theme_cls.secondaryContainerColor
                        pos_hint: {'center_y': .5}
                        
                        MDButtonText:
                            text: root.time_display
                            theme_font_size: 'Custom'
                            font_size: sp(19)
                            theme_text_color: 'Custom'
                            text_color: app.theme_cls.onSecondaryContainerColor
                            pos_hint: {'center_x': .5, 'center_y': .5}
                
                # Start and Stop buttons
                MDBoxLayout:
                    adaptive_size: True
                    orientation: 'horizontal'
                    spacing: dp(20)
                    pos_hint: {'center_x': .5}
                    padding: [0, dp(20), 0, 0]
                    
                    DefaultBtn:
                        id: start
                        text: 'START'
                        width: dp(150)
                        md_bg_color: '#253849'
                        on_press: root.confirm_functionality_test()
                        disabled: root.test_running
                    
                    DefaultBtn:
                        id: stop
                        text: 'STOP'
                        width: dp(150)
                        md_bg_color: '#253849'
                        on_press: root.stop_functionality_test()
                        disabled: not root.test_running
        
        # Continue button removed - now using the completion dialog's accept button instead
    
    # Back button
    MDBoxLayout:
        adaptive_size: True
        orientation: 'vertical'
        pos_hint: {'center_x': .5, 'center_y': .09}
        padding: [0, '27dp', 0, 0]

        BackBtn:
            on_press: root.go_back()

    StatIndicator: