#:kivy 2.3.0

<TestScreen>
    md_bg_color: app.theme_cls.onPrimaryColor

    MDNavigationLayout:

        MDScreenManager:

            MDScreen:

                TopBar:
                    id: test_screen
                    screen_title: 'TEST'

                MDBoxLayout:
                    adaptive_height: True
                    orientation: 'vertical'
                    pos_hint: {'center_x': .5, 'center_y': .5}

                    MDBoxLayout:
                        adaptive_size: True
                        orientation: 'vertical'
                        spacing: '16dp'
                        pos_hint: {'center_x': .5}

                        MDBoxLayout:
                            adaptive_size: True
                            orientation: 'horizontal'
                            pos_hint: {'center_x': .5, 'center_y':.5}
                            spacing: '16dp'

                            MDButton:
                                style: 'elevated'
                                radius: 0
                                theme_width: 'Custom'
                                width: '250dp'
                                radius: '5dp'
                                on_press:
                                    root.pin_entry = True
                                    root.open_sheet(sheet)

                                MDButtonText:
                                    id: pin_delay
                                    text: 'ADJUST'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

                            MDButton:
                                style: 'elevated'
                                radius: 0
                                theme_width: 'Custom'
                                width: '250dp'
                                radius: '5dp'
                                on_press:
                                    root.interval_entry = True
                                    root.open_sheet(sheet)

                                MDButtonText:
                                    id: run_cycle_check_interval
                                    text: 'ADJUST'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

                        MDBoxLayout:
                            adaptive_size: True
                            orientation: 'horizontal'
                            pos_hint: {'center_x': .5, 'center_y':.5}
                            spacing: '16dp'

                            MDButton:
                                style: 'elevated'
                                radius: 0
                                theme_width: 'Custom'
                                width: '250dp'
                                radius: '5dp'
                                on_press:
                                    app.calibrate_pressure_sensor()

                                MDButtonText:
                                    id: calibrate
                                    text: 'CALIBRATE SENSOR'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

                            MDButton:
                                style: 'elevated'
                                radius: 0
                                theme_width: 'Custom'
                                width: '250dp'
                                radius: '5dp'
                                on_press:
                                    app.toggle_debug()

                                MDButtonText:
                                    id: toggle
                                    text: 'TOGGLE DEBUG'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

                        MDBoxLayout:
                            adaptive_size: True
                            orientation: 'horizontal'
                            pos_hint: {'center_x': .5, 'center_y':.5}
                            spacing: '16dp'

                            MDButton:
                                style: 'elevated'
                                theme_width: 'Custom'
                                width: '250dp'
                                radius: '5dp'
                                on_press:
                                    app.restore_defaults()

                                MDButtonText:
                                    id: restore_defaults
                                    text: 'RESTORE DEFAULTS'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

                            MDButton:
                                style: 'elevated'
                                radius: 0
                                theme_width: 'Custom'
                                width: '250dp'
                                radius: '5dp'
                                on_press:
                                    app.reboot_machine()

                                MDButtonText:
                                    id: reboot_machine
                                    text: 'REBOOT MACHINE'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

                        MDBoxLayout:
                            adaptive_size: True
                            orientation: 'horizontal'
                            pos_hint: {'center_x': .5, 'center_y':.5}
                            spacing: '16dp'


                MDBoxLayout:
                    adaptive_size: True
                    padding: '10dp'
                    pos_hint: {'bottom': 1, 'right': 1}

                    MDIconButton:
                        id: stat_sheet_button
                        icon: 'help-circle-outline'
                        theme_icon_color: 'Custom'
                        icon_color: app.theme_cls.onPrimaryContainerColor
                        on_press: app.open_bottom_sheet(stat_sheet)

                MDBoxLayout:
                    adaptive_height: True
                    padding: '16dp'
                    pos_hint: {'bottom': 1, 'left': 1}

                    MDLabel:
                        text: app.debug_mode_string if app.debug else ''
                        font_style: 'Title'
                        role: 'medium'
                        theme_text_color: 'Custom'
                        text_color: app.theme_cls.errorColor

                SideBar:

        NoDragMDBottomSheet:
            id: sheet
            size_hint_y: None
            height: '320dp'
            background_color: app.theme_cls.surfaceColor
            drawer_type: 'standard'

            MDBottomSheetDragHandleButton:
                icon: 'close'
                on_release:
                    sheet.set_state('toggle')
                pos_hint: {'top': 1, 'right': 1}

            MDScrollView:
                do_scroll_x: False

                MDBoxLayout:
                    orientation: 'vertical'
                    adaptive_height: True

                    MDBoxLayout:
                        adaptive_height: True
                        pos_hint: {'center_x': .5}
                        padding: [0, '12dp', 0, '24dp']

                        MDButton:
                            style: 'text'
                            disabled: True
                            theme_width: 'Custom'
                            size_hint_x: 1

                            MDButtonText:
                                id: input_field
                                text: root.input_string
                                font_style: 'Title'
                                role: 'medium'
                                theme_disabled_color: 'Custom'
                                disabled_color: app.theme_cls.primaryColor
                                pos_hint: {'center_x': .5, 'center_y': .5}

                    MDBoxLayout:
                        adaptive_height: True
                        size_hint_x: .7
                        orientation: 'vertical'
                        spacing: '10dp'
                        pos_hint: {'center_x': .5}

                        MDBoxLayout:
                            adaptive_size: True
                            pos_hint: {'center_x': .5}
                            spacing: '10dp'
                            orientation: 'horizontal' 

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(1)

                                MDButtonText:
                                    text: '1'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(2)

                                MDButtonText:
                                    text: '2'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(3)

                                MDButtonText:
                                    text: '3'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(4)

                                MDButtonText:
                                    text: '4'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(5)

                                MDButtonText:
                                    text: '5'

                            MDButton:
                                radius: '5dp'
                                theme_width: 'Custom'
                                width: '85dp'
                                on_press: root.backspace()

                                MDButtonText:
                                    id: back
                                    text: 'BACK'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

                        MDBoxLayout:
                            adaptive_size: True
                            pos_hint: {'center_x': 0.5}
                            spacing: '10dp'
                            orientation: 'horizontal' 

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(6)

                                MDButtonText:
                                    text: '6'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(7)

                                MDButtonText:
                                    text: '7'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(8)

                                MDButtonText:
                                    text: '8'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(9)

                                MDButtonText:
                                    text: '9'

                            MDButton:
                                radius: '5dp'
                                on_press: root.add_digit(0)

                                MDButtonText:
                                    text: '0'

                            MDButton:
                                radius: '5dp'
                                theme_width: 'Custom'
                                width: '85dp'
                                on_press: root.submit()

                                MDButtonText:
                                    id: submit
                                    text: 'SUBMIT'
                                    pos_hint: {'center_x': .5, 'center_y': .5}

        Diagnostics:
            id: stat_sheet