#:kivy 2.3.0

<TestScreen>
    md_bg_color: app.theme_cls.onPrimaryColor

    MDNavigationLayout:

        MDScreenManager:

            MDScreen:

                TopBar:
                    id: test_screen
                    screen_title: 'TEST'

                MDBoxLayout:
                    spacing: '24dp'
                    pos_hint: {'center_x': .5, 'center_y': .5}
                    adaptive_size: True
                    orientation: 'vertical'

                    MDBoxLayout:
                        adaptive_size: True
                        orientation: 'vertical'
                        spacing: '4dp'
                        pos_hint: {'center_x': .5, 'center_y': .5}

                        MDButton:
                            style: 'text'
                            disabled: True

                            MDButtonText:
                                text: app.pin_delay_string
                                font_style: 'Title'
                                role: 'large'
                                theme_disabled_color: 'Custom'
                                disabled_color: app.theme_cls.onPrimaryContainerColor

                        MDButton:
                            style: 'elevated'
                            radius: 0
                            pos_hint: {'center_x': .5}
                            on_press:
                                root.pin_entry = True
                                root.open_sheet(sheet, 'modal')

                            MDButtonText:
                                id: adjust_pin_delay
                                text: 'ADJUST'

                    MDBoxLayout:
                        adaptive_size: True
                        orientation: 'horizontal'
                        spacing: '24dp'
                        pos_hint: {'center_x': .5, 'center_y': .5}

                        MDButton:
                            style: 'text'
                            disabled: True

                            MDButtonText:
                                text: app.run_cycle_check_interval_string
                                font_style: 'Title'
                                role: 'medium'
                                theme_disabled_color: 'Custom'
                                disabled_color: app.theme_cls.onPrimaryContainerColor

                    MDBoxLayout:
                        adaptive_size: True
                        orientation: 'horizontal'
                        spacing: '24dp'
                        pos_hint: {'center_x': .5, 'center_y': .5}

                        MDButton:
                            style: 'elevated'
                            radius: 0
                            pos_hint: {'center_x': .5}
                            on_press:
                                root.interval_entry = True
                                root.open_sheet(sheet, 'modal')

                            MDButtonText:
                                id: adjust_run_cycle_interval
                                text: 'ADJUST'

                    MDBoxLayout:
                        adaptive_size: True
                        orientation: 'horizontal'
                        spacing: '24dp'

                        MDButton:
                            style: 'elevated'
                            radius: 0
                            pos_hint: {'center_x': .5}
                            on_press:
                                app.toggle_debug()

                            MDButtonText:
                                id: toggle_test_cycle
                                text: 'TOGGLE TEST CYCLE'

                        MDButton:
                            style: 'elevated'
                            radius: 0
                            pos_hint: {'center_x': .5}
                            on_press:
                                app.restore_defaults()

                            MDButtonText:
                                id: restore_defaults
                                text: 'RESTORE DEFAULTS'

                SideBar:

        MDBottomSheet:
            id: sheet
            size_hint_y: None
            height: '320dp'
            background_color: app.theme_cls.surfaceColor
            drawer_type: 'standard'

            MDBottomSheetDragHandle:

                MDBottomSheetDragHandleTitle:
                    id: input_field
                    text: root.input_string
                    adaptive_height: True
                    pos_hint: {'center_y': .5}

                MDBottomSheetDragHandleButton:
                    icon: 'close'
                    on_release:
                        sheet.set_state('toggle')
                        root.pin_entry = False
                        root.interval_entry = False

            MDBoxLayout:
                orientation: 'vertical'
                padding: [0, '75dp', 0, '75dp']

                MDBoxLayout:
                    adaptive_size: True
                    pos_hint: {'center_x': 0.5}
                    spacing: '10dp'   

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(1)

                        MDButtonText:
                            text: '1'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(2)

                        MDButtonText:
                            text: '2'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(3)

                        MDButtonText:
                            text: '3'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(4)

                        MDButtonText:
                            text: '4'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(5)

                        MDButtonText:
                            text: '5'

                    MDButton:
                        radius: '5dp'
                        on_press: root.backspace()

                        MDButtonText:
                            id: back
                            text: 'BACK'

                Widget:

                MDBoxLayout:
                    adaptive_size: True
                    pos_hint: {'center_x': 0.5}
                    spacing: '10dp'   

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(6)

                        MDButtonText:
                            text: '6'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(7)

                        MDButtonText:
                            text: '7'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(8)

                        MDButtonText:
                            text: '8'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(9)

                        MDButtonText:
                            text: '9'

                    MDButton:
                        radius: '5dp'
                        on_press: root.add_digit(0)

                        MDButtonText:
                            text: '0'

                    MDButton:
                        radius: '5dp'
                        on_press: root.submit()

                        MDButtonText:
                            id: submit
                            text: 'SUBMIT'