#:kivy 2.3.0

<EfficiencyTestScreen>
    md_bg_color: app.theme_cls.onPrimaryColor

    TopBar:

    MDBoxLayout:
        adaptive_size: True
        pos_hint: {'top': .975, 'center_x': .5}

        StatusBar:

    MDBoxLayout:
        adaptive_height: True
        size_hint_x: .687
        orientation: 'vertical'
        pos_hint: {'center_x': .5, 'center_y': .5}
        spacing: '32dp'

        MDBoxLayout:
            adaptive_height: True
            orientation: 'vertical'
            pos_hint: {'center_x': .5}
            spacing: '12dp'
            padding: [0, '6dp', 0, '12dp']

            TestTextLabel:
                id: efficiency_test_description
                text: 'RUN AN EFFICIENCY TEST.'
                font_size: '20sp' if app.language == 'EN' else '17sp'
                text_color: app.theme_cls.onSecondaryContainerColor
                padding: [0, 0, 0, '4dp']

            TestTextLabel:
                id: efficiency_test_duration
                text: 'FILL/RUN LASTS 2 MINUTES, PURGE PERFORMS 6 CYCLES.'
                font_size: '15sp'

        DefaultBtnContainer:
            orientation: 'vertical'
            spacing: '4dp'

            DefaultBtn:
                id: fill_run
                text: 'FILL/RUN'
                disabled: False if not app.efficiency_test else True
                on_press: root.confirm_fill_run() if not app.efficiency_test else ''

            DefaultBtn:
                id: purge
                text: 'PURGE'
                disabled: False if not app.efficiency_test else True
                on_press: root.confirm_purge() if not app.efficiency_test else ''

            DefaultBtn:
                id: stop
                text: 'STOP'
                disabled: True if not app.efficiency_test else False
                on_press: root.stop_efficiency_test() if app.efficiency_test else ''

        MDBoxLayout:
            adaptive_size: True
            spacing: '10dp'
            pos_hint: {'center_x': .5}

            TestTextLabel:
                id: time_remaining
                text: 'TIME REMAINING:'
                font_size: '17sp'
                text_color: app.theme_cls.onSurfaceColor

            MDButton:
                radius: '2dp'
                theme_width: 'Custom'
                theme_height: 'Custom'
                width: '62dp'
                height: '30dp'
                padding: 0
                theme_bg_color: 'Custom'
                md_bg_color: app.theme_cls.secondaryContainerColor
                pos_hint: {'center_x': .5, 'center_y': .5}

                MDButtonText:
                    text: root.time_display
                    theme_font_size: 'Custom'
                    font_size: '19sp'
                    theme_text_color: 'Custom'
                    text_color: app.theme_cls.onSecondaryContainerColor
                    pos_hint: {'center_x': .5, 'center_y': .5}

    MDBoxLayout:  # Back Button
        adaptive_size: True
        orientation: 'vertical'
        pos_hint: {'center_x': .5, 'y': .06}

        BackBtn:
            on_press: app.switch_screen('System')

    FullAccessIndicator:

    StatIndicator:

    VersionIndicator:

    SideBar: